### ISSUE TITLE
lxdops import fails when the source template does not exist

### ISSUE THREAD

**Issue by melato** [melato/lxdops#10]
I have a dev.yaml lxdops file that contains:
```
#lxdops
os:
  name: alpine
  image: (server-template)
device-template: (server-template)
...
```
When I import an image that was created from dev.yaml, without .first having imported an image for server.yaml, lxdops fails with the error that there is no "server-template" property.

Import should not access device-template at all, because it recreates the filesystems from imported tar files.
When creating templates (images), they need to be created in order: first server, then dev, which may copy the server filesystems, etc.
When importing dev, there should not be a need to import server first.
